### PR TITLE
Get the latest version of a library in CDNJS from Version property

### PR DESCRIPTION
**Pull request by felipepessoto**
Fix https://github.com/aspnet/LibraryManager/issues/359

### CODE REVIEW

**Comment by fujiy** [comment]
How can I retry de CI tests?

**Comment by jodavis** [comment]
Do the tests fail when run locally, or did they only fail in the AppVeyor build?

When you open the solution locally, Visual Studio's Test Explorer window should detect all the tests, and they can be executed from there.

**Comment by jimmylewis** [comment]
FWIW, rebasing the PR should cause AppVeyor to run the tests again as well.

**Comment by felipepessoto** [comment]
Some tests are failing because unpkg.com is returning 503

**Comment by felipepessoto** [comment]
If I change the urls do https, it works:

        public const string LibraryFileListUrlFormat = "https://unpkg.com/{0}@{1}/?meta"; // http://unpkg.com/jquery@3.3.1/?meta
        public const string LatestLibraryVersonUrl = "https://unpkg.com/{0}/package.json"; // http://unpkg.com/jquery/package.json

**Comment by felipepessoto** [comment]
I think unpkg is unstable today. I already rebased, so I'll need to create another PR to trigger the tests.

The tests are OK in my machine.

Do you have something like .NET team to trigger the tests manually? For example, if I sent a message like this: "@dotnet-bot test outerloop linux x64 debug build" the tests run again.

**Comment by felipepessoto** [comment]
@jodavis, the tests worked on PR https://github.com/aspnet/LibraryManager/pull/429

**Pull request closed without merging**
