### PR TITLE
Get the latest version of a library in CDNJS from Version property

### LINKED ISSUE #359: Fix the logic to get the latest version
### Functional impact
It downloads the incorrect latest version of some libraries.

### Minimal repro steps
libman install prism

### Expected result
Install prism 1.15.0, the version that is shown when I open the library url: https://cdnjs.com/libraries/prism or when calling the API, the object root has a **Version** property that should be considered, https://api.cdnjs.com/libraries/prism:
image

### Actual result
It is installing the first version that it found in array: 9000.0.1.
https://github.com/aspnet/LibraryManager/blob/45474d37ed6977b744786e102c397b4f558a8096/src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs#L194

### Further technical details
The CDNJS API has a property to flag the current version, so we should use it.
I'll try to send a fix via pull request and create a unit test to cover this scenario.

Could you assign to me?

### PR DESCRIPTION
**Pull request by felipepessoto**
Fix #359

### CODE REVIEW

**Comment by felipepessoto** [comment]
Finally :) I got the tests running without problem

**Comment by felipepessoto** [comment]
In which VS version is this fix?

**Comment by jimmylewis** [comment]
@felipepessoto based on history, this would have been in the VS 16.0 release or the 2.0.48 version of the nuget packages.

**Comment by felipepessoto** [comment]
The issue is still happening on update menu:

image

**Comment by felipepessoto** [comment]
I created a new issue: https://github.com/aspnet/LibraryManager/issues/633

**Pull request merged**
